- name: Rollback Script
  hosts: all
  tasks:
    -
      name: "send Dynatrace the marketing campaign Rollback event"
      uri:
        url: https://{{ dynatrace_api_url }}/api/v1/events/?Api-Token={{ dynatrace_token }}
        method: POST
        headers:
          content-type: application/json
        body:
          title: Marketing Promotion Rollback
          source: Ansible for Application Deployment
          description: Rolling back after failure rate increase
          eventType: CUSTOM_DEPLOYMENT
          deploymentName: Marketing Promotion Rollback to v1.1
          deploymentVersion: v1.1
          attachRules:
            tagRule:
            - meTypes:
              - SERVICE
              tags:
              - context: KUBERNETES
                key: app
                value: carts
        body_format: json
        status_code: 200
    - 
      name: URI
      uri:
        url: http://{{ sockshop_url }}/carts/1/items/promotion/0
